export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const RESET = 'RESET';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GETALL_REQUEST = 'GETALL_REQUEST';
export const GETALL_SUCCESS = 'GETALL_SUCCESS';
export const GETALL_FAILURE = 'GETALL_FAILURE';

export const RESET_REQUESTED = 'RESET_REQUESTED';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_CHECK = 'PASSWORD_RESET_CHECK';

export const GET_USER = 'GET_USER';
export const EDIT_USER = 'EDIT_USER';
export const RESET_USER_FLAGS = 'RESET_USER_FLAGS';
export const API_USER_ERROR = 'API_USER_ERROR';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const FETCH_BUNDLE = 'FETCH_BUNDLE';
export const FETCH_BUNDLES = 'FETCH_BUNDLES';

export const RESET_TOAST = 'RESET_TOAST';
export const SET_TOAST = 'SET_TOAST';
export const SET_ERROR = 'SET_ERROR';

export const SEARCH_KITBAG_KITS = 'SEARCH_KITBAG_KITS';
export const CREATE_KITBAG_KIT = 'CREATE_KITBAG_KIT';
export const FETCH_KITBAG_KITS = 'FETCH_KITBAG_KITS';
export const FETCH_KITBAG_KIT = 'FETCH_KITBAG_KIT';
export const EDIT_KITBAG_KIT = 'EDIT_KITBAG_KIT';
export const DELETE_KITBAG_KIT = 'DELETE_KITBAG_KIT';
export const FETCH_KITBAG_LISTS = 'FETCH_KITBAG_LISTS';

export const CREATE_MARKET_KIT = 'CREATE_MARKET_KIT';
export const FETCH_MARKET_KIT = 'FETCH_MARKET_KIT';
export const EDIT_MARKET_KIT = 'EDIT_MARKET_KIT';
export const RESPOND_MARKET_KIT = 'RESPOND_MARKET_KIT';
export const DELETE_MARKET_KIT = 'DELETE_MARKET_KIT';
export const FETCH_KITBAG_MARKET_ITEMS = 'FETCH_KITBAG_MARKET_ITEMS';
export const FETCH_KITBAG_MARKET_TRADES = 'FETCH_KITBAG_MARKET_TRADES';
export const FETCH_KITBAG_MARKET_RECYCLES = 'FETCH_KITBAG_MARKET_RECYCLES';
export const FETCH_KITBAG_MARKET_FOUNDS = 'FETCH_KITBAG_MARKET_FOUNDS';
export const FETCH_KITBAG_MARKET_LOSTS = 'FETCH_KITBAG_MARKET_LOSTS';
export const FETCH_KITBAG_MARKET_STOLENS = 'FETCH_KITBAG_MARKET_STOLENS';
export const FETCH_KITBAG_MARKET_WANTEDS = 'FETCH_KITBAG_MARKET_WANTEDS';

export const ADD_IMAGE = 'ADD_IMAGE';
export const CLEAR_NEW_IMAGES = 'CLEAR_NEW_IMAGES';

export const SEARCH_MARKET_ITEMS = 'SEARCH_MARKET_ITEMS';
export const FETCH_MARKET_ITEMS = 'FETCH_MARKET_ITEMS';
export const FETCH_MARKET_ITEM = 'FETCH_MARKET_ITEM';
export const RESPOND_MARKET_ITEM = 'RESPOND_MARKET_ITEM';
export const MESSAGE_MARKET_ITEM = 'MESSAGE_MARKET_ITEM';
export const FETCH_MARKET_LISTS = 'FETCH_MARKET_LISTS';

export const SEARCH_GROUPS = 'SEARCH_GROUPS';
export const SEARCH_GROUP_MEMBERS = 'SEARCH_GROUP_MEMBERS';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_GROUP_MEMBERS = 'FETCH_GROUP_MEMBERS';
export const CREATE_GROUP = 'CREATE_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const EDIT_GROUP_STATE = 'EDIT_GROUP_STATE';
export const EDIT_GROUP_MEMBER_STATE = 'EDIT_GROUP_MEMBER_STATE';
export const DELETE_GROUP_MEMBER = 'DELETE_GROUP_MEMBER';
export const CREATE_GROUP_JOIN = 'CREATE_GROUP_JOIN';
export const EDIT_GROUP_LEAVE = 'EDIT_GROUP_LEAVE';
export const FETCH_GROUPS_MEMBER_REQUESTS = 'FETCH_GROUPS_MEMBER_REQUESTS';

export const CREATE_KITBAG = 'CREATE_KITBAG';
export const EDIT_KITBAG = 'EDIT_KITBAG';
export const FETCH_PREFERRED_KITBAG = 'FETCH_PREFERRED_KITBAG';
export const FETCH_KITBAG = 'FETCH_KITBAG';
export const FETCH_KITBAG_MEMBERS = 'FETCH_KITBAG_MEMBERS';
export const CLEAR_KITBAG = 'CLEAR_KITBAG';
export const EDIT_KITBAG_STATE = 'EDIT_KITBAG_STATE';
export const EDIT_KITBAG_MEMBER_STATE = 'EDIT_KITBAG_MEMBER_STATE';
export const CREATE_KITBAG_INVITE = 'CREATE_KITBAG_INVITE';
export const EDIT_KITBAG_LEAVE = 'EDIT_KITBAG_LEAVE';

export const FETCH_SHOW_GROUP = 'FETCH_SHOW_GROUP';
export const FETCH_SHOW_MARKET_TRADES = 'FETCH_SHOW_MARKET_TRADES';
export const FETCH_SHOW_MARKET_RECYCLES = 'FETCH_SHOW_MARKET_RECYCLES';
export const FETCH_SHOW_MARKET_FOUNDS = 'FETCH_SHOW_MARKET_FOUNDS';
export const FETCH_SHOW_MARKET_LOSTS = 'FETCH_SHOW_MARKET_LOSTS';
export const FETCH_SHOW_MARKET_STOLENS = 'FETCH_SHOW_MARKET_STOLENS';
export const FETCH_SHOW_MARKET_WANTEDS = 'FETCH_SHOW_MARKET_WANTEDS';

export const FETCH_CONTENT = 'FETCH_CONTENT';
export const ERR_CONTENT = 'ERR_CONTENT';

export const LOADING = 'LOADING';

export const API_ERROR = 'API_ERROR';
